added typescript type definitions
FreeTubeApp/yt-channel-info pull request #17
Opened 2021-02-20 23:11 UTC by Kylof61034

2021-09-21 02:04 UTC, PikachuEXE requested changes

2021-09-21 02:04 UTC, PikachuEXE commented on index.d.ts
> +        static getChannelInfo(channelId: string): Promise<ChannelInfo>;
Seems missing optional argument `channelIdType`

Same for many methods below

2021-09-21 02:04 UTC, PikachuEXE commented on index.d.ts
> +        static getChannelVideos(channelId: string, sortBy?: "newest" | "oldest" | "popular"): Promise<ChannelInfoResponse<Video>>;
Seems missing optional argument `channelIdType`

2021-09-21 02:04 UTC, PikachuEXE commented on index.d.ts
> +        static getChannelPlaylistInfo(channelId: string, sortBy?: "last" | "oldest" | "newest"): Promise<ChannelInfoResponse<Playlist>>;
Seems missing optional argument `channelIdType`

2021-09-21 02:04 UTC, PikachuEXE commented on index.d.ts
> +    }
Can't find `getChannelCommunityPosts` or `getChannelCommunityPostsMore`

2021-10-03 16:32 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Maybe also take this one over. Author hasn't been very active on GH.

2021-11-08 02:24 UTC, PikachuEXE submitted a review, later dismissed
I cannot be sure all content in `index.d.ts` matches the doc (Too long to review all)
But since it can always be fixed later I will approve

2021-11-08 08:33 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed

2021-11-16 07:21 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed

2021-11-16 07:45 UTC, PikachuEXE submitted a review, later dismissed

2021-12-15 00:40 UTC, Slayug commented
Are the last reviewers are aware of this ?  
Do you think it possible to bypass all requirements ?

2021-12-15 01:39 UTC, PikachuEXE commented
The dev team might be on vacation in Dec.
Thanks for checking the progress I think they will be back in Jan.
Is there any urgent need for this to be merged?

2021-12-15 22:35 UTC, Slayug reviewed
better usage of comment fields

2021-12-15 22:35 UTC, Slayug commented on index.d.ts
> +        continuation: string | null; // Will return null if no more results can be found.  Used with getChannelPlaylistsMore()
```suggestion
        /**
        * Will be null if no more results can be found.  Used with getChannelPlaylistsMore()
        */
        continuation: string | null;
```
It's better to use multi-line comment to have the code helper on hover

2021-12-15 22:35 UTC, Slayug commented on index.d.ts
> +        authorBanners: Image[] | null; // Will return null if none exist
```suggestion
        /**
        * Is null if none exist
        **/
        authorBanners: Image[] | null;
```

2021-12-15 22:35 UTC, Slayug commented on index.d.ts
> +        authorThumbnails: Image[] | null; // Will return null if none exist
```suggestion
        /**
        * Is null if none exist
        **/
        authorThumbnails: Image[] | null;
```

2021-12-15 22:37 UTC, Slayug commented
@PikachuEXE thought dev team was inactive because there is no activity since october

2021-12-15 22:55 UTC, ChunkyProgrammer commented
> @PikachuEXE thought dev team was inactive because there is no activity since october

I think the team has just been extra busy recently with work, school and personal stuff

2021-12-16 01:48 UTC, PikachuEXE commented
I don't check this repo at all unless got mentioned / review requested
I normally only check the main repo (if I remember to)

There are also a lot of issues/PR on main repo which also drains away our attention
So if there is a good reason to raise the urgency of this PR, feel free to state / discuss here (I think I am active for discussion at least)
But let's also adjust the expectation of dev team availability

Most of us don't get paid (or not much) to maintain open source projects, meaning it's charity work
And I got multiple (not just this) open source projects to handle and a day job to take care
I can respond within a week or even a day mostly, but no guarantee
I would expect the other can be busier than me

2022-01-05 02:02 UTC, PikachuEXE submitted a review, later dismissed

2022-01-05 10:56 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed

2022-06-08 01:26 UTC, ChunkyProgrammer commented
> Why would this PR also update `app/youtube-grabber.js`?

I'm not sure, seems to be some merge issue

2022-08-23 02:55 UTC, PikachuEXE commented
CI failed due to service returning 503, not related

2022-08-23 02:55 UTC, PikachuEXE approved these changes

2022-08-24 13:00 UTC, absidue approved these changes

2022-08-24 13:16 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-08-24 13:16 UTC, merged