Returning an object instead of error on non-existing channels
FreeTubeApp/yt-channel-info pull request #46
Opened 2021-08-24 02:58 UTC by jasonhenriquez

**Relevant issue**
closes #33

**Description**
The functions `getChannelInfo` and `getChannelVideos` will now return the alert message given by a response as the sole property of the return object upon loading a non-existent (e.g., removed, banned) channel. Formerly, `getChannelInfo` threw a rejected Promise object with the response alert text, and `getChannelVideos` did not check for this case at all (thus, it annoyingly returned `TypeError: Cannot read property 'channelMetadataRenderer' of undefined #33`). The README is updated accordingly with the new usage of the aforementioned functions (as well as the commented-out `throw response.alert` which informs developers how to maintain the old error design flow).

This PR should now handle the common case of a deleted or banned channel (or attempting to load the videos of such a channel) more elegantly. Here are three reasons for this design in the words of @GilgusMaximus:
> 
> - Other package users can check the documentation on what a status code means more easily than long exceptions
> - If we leave in an exception, we can't tell whether it is a new bug or an old bug
> - Exception handling makes code more complex + less easy to read and therefore can be abstracted by the module to avoid it in the main code base

2021-09-18 13:58 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2021-09-18 22:40 UTC, PikachuEXE commented on README.md
> +   alert: String, // Will return a response alert message if any (e.g., "This channel does not exist."). Otherwise null
What do you think about naming it as `alertMessage`/`alertMsg`?
I image `alert` being an object with multiple properties, like `error`.

2021-09-25 19:11 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
I think u need to change to development in order to get this merged.

2021-09-25 20:54 UTC, peepopoggers approved these changes

2021-09-26 01:08 UTC, PikachuEXE requested changes

2021-09-26 01:08 UTC, PikachuEXE commented on app/helper.js
> +        alert: response.data[1].response.alerts[0].alertRenderer.text.simpleText
You can see when you pull the message via `response.data[1].response.alerts[0].alertRenderer.text.simpleText`
`response.alerts` is an array of object not strings
Which is why the "alert message/text" should be named `alertMessage`/`alertText`

2021-09-30 04:49 UTC, peepopoggers submitted a review, later dismissed
LGTM

2021-09-30 05:56 UTC, PikachuEXE submitted a review, later dismissed
@jasonhenriquez 
You forgot to re-request review 😅

2021-10-03 03:58 UTC, ChunkyProgrammer approved these changes

2021-10-03 03:58 UTC, ChunkyProgrammer commented on README.md
> +   alertMessage: String, // Will return a response alert message if any (e.g., "This channel does not exist."). Otherwise null
undefined not null

2021-10-03 03:58 UTC, ChunkyProgrammer commented on README.md
> +   alertMessage: String, // Will return a response alert message if any (e.g., "This channel does not exist."). Otherwise null
undefined not null

2021-10-03 13:52 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2021-10-03 16:07 UTC, peepopoggers approved these changes

2021-10-03 16:33 UTC, ChunkyProgrammer approved these changes

2021-10-03 16:34 UTC, merged