Extract Channel Links through getChannelInfo
FreeTubeApp/yt-channel-info pull request #53
Opened 2021-11-07 00:34 UTC by ChunkyProgrammer

This PR will allow channel links to be extracted ex: a channel's FaceBook link, Instagram, Merch store

2021-11-30 21:52 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed

2022-01-07 03:55 UTC, PikachuEXE requested changes

2022-01-07 03:55 UTC, PikachuEXE commented on README.md
> +      primaryLinks: Array[Object],
I think `Object` should be replaced with the possible properties of objects?

2022-01-07 03:55 UTC, PikachuEXE commented on app/youtube-grabber.js
> +    }
Would be good to separate variables for result and temp storage (for readability or something)
`links` is for result and `channelHeaderLinksData` is temp storage
```suggestion
    const links = {
      primaryLinks: [],
      secondaryLinks: []
    }
    if (typeof headerLinks !== 'undefined') {
      const channelHeaderLinksData = headerLinks.channelHeaderLinksRenderer
      links.primaryLinks = channelHeaderLinksData.primaryLinks.map(x => {
        return {
          url: decodeURIComponent(x.navigationEndpoint.urlEndpoint.url.match('&q=(.*)')[1]),
          icon: x.icon.thumbnails[0].url,
          title: x.title.simpleText
        }
      })
      links.secondaryLinks = channelHeaderLinksData.secondaryLinks.map(x => {
        return {
          url: decodeURIComponent(x.navigationEndpoint.urlEndpoint.url.match('&q=(.*)')[1]),
          icon: x.icon.thumbnails[0].url,
          title: x.title.simpleText
        }
      })
    }
```

2022-02-08 02:02 UTC, PrestonN commented
Please make the changes that @PikachuEXE mentioned and then I'll be good to merge this.

2022-02-08 02:19 UTC, PrestonN commented
Actually never mind, GitHub allows me to commit them with the click of a button.

2022-02-08 02:20 UTC, merged