Fix for channels with no secondary links
FreeTubeApp/yt-channel-info pull request #61
Opened 2022-02-28 22:57 UTC by SuperFurryCoder

I had a channel with only primary links, causing the error:

debug TypeError: Cannot read property 'map' of undefined
debug at Function.getChannelInfo (///node_modules/yt-channel-info/app/youtube-grabber.js:40:68)

The structure of 'links' at that point was:
{
primaryLinks: [ { navigationEndpoint: [Object], icon: [Object], title: [Object] } ]
}
rather than:
{
primaryLinks: [ { navigationEndpoint: [Object], icon: [Object], title: [Object] } ],
secondaryLinks: [ { navigationEndpoint: [Object], icon: [Object], title: [Object] } ]
}

Not sure if you need to create empty secondaryLinks array instead at that point, but this fix works fine for me.

2022-02-28 23:04 UTC, ChunkyProgrammer commented
Empty secondaryLinks array is created here https://github.com/FreeTubeApp/yt-channel-info/blob/f4a85e0d7dbade1983c9c1a890b85f3bda7b56ff/app/youtube-grabber.js#L28

This fix looks good to me. Thanks for taking the time to create a PR.

2022-02-28 23:04 UTC, ChunkyProgrammer approved these changes

2022-03-01 01:45 UTC, PikachuEXE requested changes

2022-03-01 01:45 UTC, PikachuEXE commented on app/youtube-grabber.js
> +
We probably shouldn't have these spaces added here
```suggestion

```

2022-03-14 21:04 UTC, ChunkyProgrammer commented
They don't seem to be active on GitHub so i will commit the change

2022-03-15 02:16 UTC, PikachuEXE commented
@ChunkyProgrammer Ya but why remove the blank line, just removing the spaces is fine 😬

2022-03-15 03:00 UTC, ChunkyProgrammer commented
Idk i just did the "commit suggestion" feature on github

2022-03-15 06:14 UTC, PikachuEXE approved these changes
OK I guess it's GH fault

2022-03-15 10:54 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-03-15 20:07 UTC, merged