fix shorts regex
FreeTubeApp/yt-channel-info pull request #81
Opened 2022-06-23 19:23 UTC by ChunkyProgrammer

This should fix the issue, didn't have time to test

2022-07-04 21:09 UTC, ChunkyProgrammer commented
not sure why it's failing exactly

2022-07-06 17:24 UTC, GilgusMaximus commented
I guess here we can just apply the same code logic then as over at the other module

2022-07-14 14:22 UTC, GilgusMaximus commented
@ChunkyProgrammer use npm to do the package install and then the ci should run smoothly

2022-07-14 14:28 UTC, ChunkyProgrammer commented
> @ChunkyProgrammer use npm to do the package install and then the ci should run smoothly

done

2022-07-14 14:36 UTC, GilgusMaximus submitted a review, later dismissed
Same as over at yt-trending-scraper

2022-07-15 02:40 UTC, PikachuEXE requested changes
Also I have no idea how to test this

2022-07-15 02:40 UTC, PikachuEXE commented on app/helper.js
> +          lengthSeconds = parseInt(numbersOnly[numbersOnly.length - 2])
I can't understand this logic until I see an example value :S
```suggestion
          // Example value for 1 minute: `xxxxxx`
          // Example value for less than 1 minute: `xxxxxx`
          lengthSeconds = parseInt(numbersOnly[numbersOnly.length - 2])
```

2022-08-12 00:36 UTC, PikachuEXE approved these changes

2022-08-16 03:26 UTC, ChunkyProgrammer commented
@absidue updated description

2022-08-16 09:44 UTC, absidue approved these changes

2022-08-16 10:26 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-08-16 10:26 UTC, merged