Improve Home page parser
FreeTubeApp/yt-channel-info pull request #87
Opened 2022-08-12 03:15 UTC by ChunkyProgrammer

- Should properly parse YouTube explore pages
- Move some logic to helper file
- Use regex.test instead of string.match

2022-08-12 03:16 UTC, ChunkyProgrammer commented
#81 will need to be merged for CI and Test to pass

2022-08-16 11:37 UTC, PikachuEXE approved these changes

2022-08-16 11:48 UTC, absidue requested changes
Please simply the RexExp code. The rest of it looks good.

2022-08-16 11:48 UTC, absidue commented on app/helper.js
> +      } else if (new RegExp(/\?list=/).test(shelfUrl)) {
you don't need to wrap `/regex/` in `new RegExp()`, as `/expression/` is the literal notation to create a `RegExp` object. It's like doing `new String('the string')`.

2022-08-16 13:31 UTC, absidue approved these changes

2022-08-16 14:30 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-08-17 01:28 UTC, PikachuEXE approved these changes

2022-08-17 01:28 UTC, merged