Fix linter issues, add linter workflow
FreeTubeApp/yt-channel-info pull request #88
Opened 2022-08-23 03:04 UTC by ChunkyProgrammer

2022-08-23 15:22 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed

2022-08-24 01:16 UTC, PikachuEXE submitted a review, later dismissed

2022-08-24 02:19 UTC, PikachuEXE approved these changes

2022-08-24 07:22 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-08-24 13:05 UTC, absidue requested changes

2022-08-24 13:05 UTC, absidue commented on .github/workflows/linter.yml
> +      uses: actions/setup-node@v2
```suggestion
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
```

2022-08-24 13:07 UTC, absidue approved these changes

2022-08-24 13:07 UTC, absidue approved these changes

2022-08-24 13:08 UTC, absidue approved these changes

2022-08-24 13:16 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-08-24 13:31 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@PikachuEXE use your thunderbolt approval move

2022-08-24 13:51 UTC, PikachuEXE approved these changes
Almost 10pm = =

2022-08-24 13:51 UTC, merged